[project]
name = "cashflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ruff>=0.13.3",
    "yfinance>=0.2.66",
    "pandas>=2.0.0",
    "pyarrow>=10.0.0",
]
